---
title: "Find Efran article"
author: "bh"
date: "`r Sys.Date()`"
output: html_document
bibliography: [General_references.bib]
css: style.css
---


Let’s use that Efran, Lukens, and Greene (2007) article.

1. Go to [North’s Article page](https://libguides.northseattle.edu/welcome/articles){target='_blank'} and click on the periodical locator.

2. Type in the name of the periodical for Efran’s piece.

You will see a link with the periodical’s name. Go ahead and click on this but beware of the next instruction:

3. Once you have clicked on that link you may want to start searching within that publication. But do not do that. Instead, notice a little bit further down the search box you should see something that says “View online” and beneath that you should see something that says “proquest research library”. It’s this piece we need.

   That Proquest research library is the database that you’ve all paid fees to access. So you need to remember that database name. Or, I think now you can just click on it and skip to step 8.

4. While remembering that database name, you need to go back to [North’s Article page](https://libguides.northseattle.edu/welcome/articles){target='_blank'}

5. Notice what is presented here. You can see Periodical locator, but notice “A to Z” list of databases. (You might also notice just below two links; one to academic search and the other to Proquest).

6. Click on “A to Z”

7. You might notice that there are 67 databases that North Seattle has premium access to. In our case we’re going to be looking for the proquest direct database. And we can either click on the letter “P” or we can just type in proquest direct.

```{block,type='blueBackground'}

Note on Popular sources

You may also notice the little tag “popular” next to proquest link. That’s an indicator that the articles are not peer reviewed and so aren’t exactly cutting edge science. Even though this particular journal we are looking for, Psychotherapy Networker, is flagged as a popular type, it is a place for therapists to share their thoughts on the profession so there is a lot of value in it.

For help in distinguishing the different types of sources, the library has some guides:

  [Scholar vs popular](http://libguides.northseattle.edu/c.php?g=97441&p=630690){target='_blank'}

  [Find Scholarly Journals](http://libguides.northseattle.edu/c.php?g=97441&p=630669){target='_blank'}
```

8. Opening Proquest from your home, or remotely, you will need to validate your credentials. In other words, you need to prove that your are in fact a student of North Seattle before you can continue, which is why you’ve been prompted for your @ seattlecolleges.edu email and password. Once you do that you’ll then be able to see inside of the proquest database. Then you can now search for the article.

    * 8a. If you don’t know your @ seattlecolleges.edu email, or email password, you can go to this location https://tools.seattlecolleges.edu/Initialize/resetmypassword to update it, reset/change the password. If you still can’t get access, let me know.

9. You should see a simple search box, where you can enter important bits of information. I often start with the author’s last name, in this case, Efran,and then some unique identifying feature of the article. A few key words of the article title, or perhaps the full article title will be useful.

But notice that next to the text boxes there are drop down menus. You need to use those, otherwise the search engine will just search for your terms anywhere in the document and will provide too many ‘hits’. Instead, you should indicate ‘Efran’ as author, and “defining” in the document title. (of course, you could search any way you like).

When you search for those two terms in their respective fields, you will get two hits and one of them is the article we need. You should notice that it is a full text, not all databases provide full text documents. But in this case it’s a full text. You can either print it or read it online.

Yay. Now you can find the other articles.