---
title: "Week 9"
author: "Brian Holt"
date: "`r Sys.Date()`"
output:
  html_document:
   anchor_sections: TRUE
   css: style.css
   toc: true
   toc_float: true
   config:
bibliography: [General_references.bib]
biblio-style: apalike
link-citations: yes
---


# Week 9 Personality Nov 20 {#Week9}

Lots here.  One thing will be an assignment for you creating a very short survey.

## Survey assignment

See [instructional video here](){target='_blank'}

See [worksheet for steps](){target='_blank'}

## Personality

This week is an introduction to personality.

You will want to read the textbook and to keep some ideas in mind.

The first is that there's basically four major theories of personality.  [However, there are others](https://en.wikipedia.org/wiki/Personality_psychology#:~:text=The%20major%20theories%20include%20dispositional,instead%20take%20an%20eclectic%20approach){target='_blank'}.  There are also offshoots and sub theories.

The four major theories that I think of include psychoanalysis (with several sub-types often associated with particular people), Humanistic (with existentialism as a sub-type), Cognitive-behavioral, and finally Trait/dispositional approaches (the Big-5 being the most researched).

The second thing to be aware of is that there are several persistent and likely impossible problems to solve in studying personality. The classic example: "is a behavior the consequent of a person's personality--like an internal trait system, or is that behavior a result of environmental influence?"



|Here are these persistent problems I mentioned:
|:---|
|1.  <span class='underline'>Mind/body</span>-- Descartes split body from mind with his "I think therefore I am" bit.  Some know this as Cartesian dualism, the viewpoint that mind and body are separate things.  Body has matter, mind does not, and therefore not subject to scrutiny.  Dualism fosters reductionism, the attempt to discover ‘truth’ by breaking things down into simpler units.  In personality, we often talk about motivation and so a question that comes up is whether mind has anything to do with it...but right away, then, you are locked into a dualism. 
|2. <span class='underline'>Person vs situation</span>-- Both are correct.  But for decades this was (and sometimes still is) the big friction within Personality studies.  Behavioral psychologists tend to de-emphasize  "person variables" as unimportant and insist that situations are responsible for eliciting, shaping, etc behavior.  On the other hand, Personologists tend to de-emphasize situational factors as “nuisance variables or noise”.  The debate is basically a draw.
|3. <span class='underline'>Nature vs nurture</span>-- what is **THE** cause?  Studying personality requires an acceptance of both causes are necessary.  Another way to say this is that all behavior is 100% nature and 100% nurture because our biology doesn't live in a vacuum; our biology develops in an environment and will be sensitive to that environment. 
|4. <span class='underline'>Determinism vs freedom</span>-- Mostly self explanatory; to what degree do we actually choose our behaviors?  Free will is hard to study in the lab and philosophically difficult to prove (I'm trusting what philosophers tell me).
|5. <span class='underline'>Stability vs change</span>-- personality traits consistently show stability.  However, this does not mean uniformity.  Here is one of those places I think one needs to think of interaction effects.  So, personality seems to be quite stable after your mid 20's, probably due to some biological maturation (eg, impulse control), but major life events, traumas, psychotherapy can also bring about some personality change.  
|6. <span class='underline'>Reification</span>--  treating a hypothetical construct as real. Intelligence is a hypothetical construct.  It can be used to predict behavior pretty well, sometimes, for some people, but it’s not a real ‘thing’.  Making it real would be to reify it. 
|7. <span class='underline'>Extrapolation</span>--  this is extending known data into new areas. Lots of science occurs in the lab in order to control variables and to determine effect sizes, but in the end we want to see the degree to which their findings apply to the real world.  Often this shows up when studying ‘micro’ behaviors, as in how do neurons actually affect social situations.
|8. <span class='underline'>Diversity</span>-- You will see that personality theorists often project their own personality and experiences into their theories. And given a lack of diversity in psychology for the past 100 years it’s fair to say that these theories may be lacking pluralistic values.

## Read/Watch

* [Read the following example of how plagiarism is easy to commit](https://docs.google.com/document/d/1_-FUu6dDQC9FL38jCeRGMaXPq57PF6AsxczwZY4Hlpw/edit#){target='_blank'}

* [Personality Chapter Textbook](https://openstax.org/books/psychology-2e/pages/11-introduction){target='_blank'}

* Video's on personality (about 1.6 hours) 
  * [Personality part 1](https://youtu.be/IhYt6xhG-6Q){target='_blank'}
  
  * [Personality part 2](https://youtu.be/0lJqfoT-W0Y){target='_blank'}
  
  * [Personality part 3 on Freud](  https://youtu.be/CHtoonRN4uU){target='_blank'}
  
  * [Personality part 4 on existentialism](https://youtu.be/np-drb_tjuA){target='_blank'}

```{block,type='blueBackground'}
Please don't skip these following videos/pods--stroke of insight and words.  Let me know if the links don't work for you. 
```

* [Stroke of Insight](https://www.youtube.com/watch?v=QTrJqmKoveU){target='_blank'}    about 20 minutes

* [radiolab on words](http://www.radiolab.org/story/91725-words/){target='_blank'}    about 60 minutes (3 segments)

## Do the following

* [take the big 5 test here](http://www.personalitytest.net/ipip/index.html){target='_blank'}
    * There are 2 versions to choose from, a short and long.
    * You may want to save your output for posterity.  The output should include your score on the 5 dimensions (OCEAN) plus 6 sub-tests for a total of 30 results.
    ```{block,type='instructorNote'}
    Don't publish this in your one-doc to rule...You can if you want but it is somewhat private information. 
    ```
* In 1- 2 pages, respond to the prompt: "what do we mean by ‘identity’?"
    * If you use chatGPT, do not have it write this for you.  I will know because I've already given the prompt to it.  If you have gpt write the answer for you, I'll catch and report your plagiarism.
      * my hope is that people won't cheat like this because there are no points lost for mistakes. 
    * You can use chatGPT to help you think about your work.  Ask it questions. That is fine. Just don't let it do the work for you. 
    * Be clear about your constructs,
    * use research outside (in addition to the above sources) of the things listed above,
    * support your thinking about what identity means.  (support means use the critical thinking standards)
    * use what we’ve covered anywhere in the course.
    * This is an impossible assignment, which means that it's huge.  You can't do a comprehensive job.  You have to pick your approach, decide on what to include or exclude. Just be transparent about it)
* Post your work in the [#week-9](https://canvas.seattlecolleges.edu/courses/16702/modules/items/780111){target='_blank'} channel
* Comment with the intent to engage 1-2 of your classmates and their writing.


```{block,type='blueBackground'}
Another way to think about this assignment:   If students take an intro to psych class, should they not be able to reasonably answer the question "what is identity?"  Not exhaustively answer it, not write a master's thesis, but to be able to point to the complexity of the problem while still committing to some conclusion.
```


<!-- * Re-Read/skim Nancy Chick, [Metacognition](https://cft.vanderbilt.edu/guides-sub-pages/metacognition/){target="_blank"} -->

<!-- * Re-Read/skim Alfie Kohn, [The Case Against Grades](https://www.alfiekohn.org/article/case-grades/){target="_blank"} -->

<!-- * [Do A self-reflection Survey--be sure to select week 9 self-reflection](https://docs.google.com/forms/d/e/1FAIpQLSdCKXCNvH-nSdnuCz0OrFUcQPZXVEugR4D5lyBiZzNKYVkANw/viewform?usp=sf_link){target="_blank"} -->

<!--     * the text boxes you see in this survey will expand to accommodate what you need to write.  In other words, don't feel like you must only say like 3 words to just fit the box shown. -->



<!-- # Optional assignment on Killmonger -->

<!-- Last quarter I made an offhand comment about killmonger from the marvel movie universe.  It was in the context of a need to operational define terms like villain, hero, tragic hero, etc. -->

<!-- I offer it as an optional but different opportunity to think about psychology and to demonstrate critical thinking.  -->

<!-- ## [Is Killmonger a villian or a tragic hero?](https://docs.google.com/document/d/1PQ4GopLAz2gnCf6RH3PjAdjAepYdgpMdUeIwEPNEkbY/edit?usp=sharing){target='_blank'}  -->



Again, it's optional and not obviously connected to Psychology but a reasonable argument that it's related to personality, abnormal Psych, and social psych could be made.  You don't have to make a connection to psychology, but if you do this assignment, you really should use a workflow and the critical thinking standards.


`r if (knitr:::is_html_output()) '
# References {-}
'`



