---
title: "Week 2 Mon_Wed"
author: "Brian Holt"
date: "`r Sys.Date()`"
output:
  html_document:
   anchor_sections: TRUE
   css: style.css
   toc: true
   toc_float: true
   config:
bibliography: [General_references.bib]
biblio-style: apalike
link-citations: yes
---


# Week 2 Oct 2  {#Week2}


## Orienting comment

If you're relatively new to taking college classes, you might find it disconcerting that we don't simply have you remember a list of vocabulary words. Sometimes memorization is good. In psychology, as an example, the term "negative reinforcement" is often confused with a form of punishment.  It's not.  Can't be. Punishment is not reinforcement. But that's a digression.

Memory is a relatively shallow level of knowledge. Check out this simple hierarchy pertaining to thinking: [Bloom's taxonomy ](https://uwaterloo.ca/centre-for-teaching-excellence/blooms-taxonomy-learning-activities-and-assessments){target="_blank"} [-@centreforteachingexcellenceBloomTaxonomyLearning2019].  If you expand the "cognitive domain" you'll see that remembering and understanding are pretty low on this scale.  There are other scales out there, but Bloom is well known.

You might also notice that summary is much lower than synthesis, which is way over under "create".

Back to my point, vocabulary is a very low level type of knowledge. It's not without importance. The more you immerse yourself into a discipline, you'll need to know the vocab for efficient/accurate information.  But that will come while you are in your groove.

And, so, the reasons that human beings create schools and classes, such as ours, is to learn things in a deeper way.

You may be interested to know in Psychology, what causes attention deficit hyperactivity disorder. You might wonder what causes bipolar disorder or why is it that you enjoy one type of activity but somebody else does not. Or perhaps how it is that certain romantic partners get along while others do not. These are all interesting questions and curiosities.

The moment you start getting into those questions, it would be nice if there were short answers but those short answers are usually simplistic and shallow.

So we have to practice, and it is a practice--you don't just get an education and stop learning--you have to keep practicing what you know and how you know it. And it turns out that 'how you know something' is a philosophical question.

So, week 2 is going to be a lot to do with philosophy. It overlaps a little bit with the materials you watched during week one. But the idea is that you're going to have to reflect a little bit about this epistemological question: how do you know what you know?

```{block, Dangers of URLs, type='blueBackground'}
<span class='underline'>Note on References and only using URLs</span>

Your instructor will frequently remind you to not rely on URLs when referencing. If the URL is available, you should include it in the reference, but whenever you are supporting a claim with a reference you should fill out the full reference, including the author, the year it was published, its title, and the publisher. The reason is that URLs will change from time to time as this happened to your instructor with the bloom taxonomy link.
```


## Read Some stuff

1. Re-read the critical thinking items in the syllabus
    * Write them in your one document to rule them all and give a one-sentence description of each **using your own words.**

2. Read/skim [Chapter 2 of your textbook](https://openstax.org/books/psychology-2e/pages/2-introduction){target="_blank"}.  This means you should read the first page and the summary page of the chapter, and then skim the chapter for things relevant to your work or interests.  Take notes on what you find. You can put them into the google doc if you want.

3. Read @Schwartz1771, [The importance of stupidity in scientific research
](https://jcs.biologists.org/content/121/11/1771){target='_blank'}

4. Read [Red scare evaluation](https://docs.google.com/document/d/1-g6-uJELM5zgb-yTRCQ8Ah76P9FccFZ_V2GK6YwP3iw/edit?usp=sharing){target='_blank'}


## Do the following
0. reminder to write down descriptions of the critical thinking standards in your own words.
1. write a synthesis of the 4 sources above (critical thinking, stupidity in science, red scare evaluation, chapter 2).  You may want to consider a comment about whether you think knowledge is static.

```{block, type='blueBackground'}

Please do not summarise these articles.  Synthesize.  Use the lecture just below to help
```

  * [Lecture on one way to write a synthesis paper--This should pop-up a new tab/window but you'll have to log in to canvas because that is how the videos are stored.](https://northseattle.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=44737fc2-c8cb-4286-9dcf-ac4b011de256){target='_blank'}


2. Put your writing into the 'one doc to rule them all'.  Give that page a new heading, a title. Highlight that title and go to the 'insert' menu item and insert "bookmark".  You should see a little blue ribbon and a "link" that you can copy and paste into slack...

3. Share your work on slack by linking to it in the canvas Discussion #[week-2 completed work](https://canvas.seattlecolleges.edu/courses/16707/discussion_topics/156341?module_item_id=740396){target='_blank'}.

4. Read and comment upon some of your classmates submissions.  In google docs, you can highlight any part of their page and then create a comment by right clicking or using the keyboard shortcut "Ctrl + alt + m"

5. Please fill out this [Importance of Sexuality Survey](https://docs.google.com/forms/d/e/1FAIpQLSfpnmmTRSjBNa50tTLHsUX3venfF8aTe85CCXVha6cFeO_Sew/viewform?usp=sf_link){target='_blank'}.  It is anonymous. I do not collect information that can be personally tied to you. If you are logged into your google account, google will show you your email address and say that you can use your account to 'store' your work so that you can come back to it. But that's google and not the survey.  I don't track your email.

* It's not required, but it's helpful for my classes because it is useful to see how surveys are supposed to work.

## Conversation Questions

These are questions that I'd like to discuss in class/zoom sessions.  I think that if you've done the reading/watching of videos, you may have the ability to contribute to the conversation.

A) What is the confirmation bias?
B) What is a workflow?
C) What value is there in synthesizing information?

