---
title: "Week 10"
author: "Brian Holt"
date: "`r Sys.Date()`"
output:
  html_document:
   anchor_sections: TRUE
   css: style.css
   toc: true
   toc_float: true
   config:
bibliography: [General_references.bib]
biblio-style: apalike
link-citations: yes
---

# Week 10 Abnormal Dec 1 {#Week10}

<!-- ## Be sure to check out Week 11 on social psychology -->

<!-- As an assignment it may be taxing so you'll want to plan out your next few weeks -->

## Abnormal Psych

Abnormal psychology has a lot of hidden dangers. Which means I have a responsibility to call out a couple of things in a way that's different than past weeks.

First thing is to Beware of the medical student syndrome. This is the tendency for medical students to self-diagnose when learning about new and exotic illnesses. The same thing happens in Abnormal psychology. The profession tries to make diagnosis clear to those who actually make diagnoses. But that means that non-experts will overestimate their own ability to accurately diagnose self and others.

So please don't. Don't diagnose yourself and don't diagnose others.  If you think that you or someone you know struggling with a mental disorder don't try to diagnose them or even offer advice. Instead ask them what they need, and listen.

## Read/Watch

 * Personality and test/measures (added soon)

 * [Epidemiology](https://youtu.be/y_ZbB-RoQ3g){target='_blank'}

* [ADHD youtube primer, about 30 minutes](https://www.youtube.com/watch?v=ouZrZa5pLXk){target='_blank'}
  * if you ever wondered if you have ADHD, this might be helpful (thought don't diagnose yourself with just this video. You need a trained diagnostician to do it right).

* [Abnormal Psych Chapter Textbook](https://openstax.org/books/psychology-2e/pages/15-introduction){target='_blank'}

* @efran_defining_2007 This has some nice controversial and provocative ideas.  Not everyone will like them. You'll need to look this up using the Library's database.  


The specific database is called Pro-quest.  [This schedule has instructions for doing this](https://docs.google.com/document/d/1C3DpmbeqthCICzL90UbJ_81PJDSrMrq1NTe3FxEdnMQ/edit?tab=t.0){target='_blank'}




* [Lecture on Diathesis Stress Model](https://youtu.be/1MaaORgCHvc){target='_blank'}   15 minutes

* [Lecture on how anxiety is about survival](https://youtu.be/bVdEGLSmXlk){target='_blank'}   7 minutes

  * [slides on anxiety](https://docs.google.com/presentation/d/1GGtnthIVhvoOaDVTddAdgcyK7osdGebq4K0Fc_KhlCc/edit?usp=sharing){target='_blank'}

* [Optional Lectures on depression](https://www.youtube.com/playlist?list=PLDEwZwMNQswsr6gT7c0HT9rbpW5X-lstj){target='_blank'}  50 minutes'ish

* [Schizophrenia, and whether cannabis is related](https://youtu.be/W7sAkrHsrmg){target='_blank'} 
 
   * [slides on schizophrenia  --- 25 minutes](https://docs.google.com/presentation/d/1vb9YPOa75W2I00sKs_RzNP7WcQ_2WUdiBKgsja8bnQI/edit?usp=sharing){target='_blank'} 

* [Optional case study interview of a person suffering from Schizophrenia](https://youtu.be/bqBbGoN-dWE){target='_blank'} 7 min

* Questions to ask yourself when thinking about abnormal psychology

  * What is normal versus abnormal?  What does the textbook say? What is missing?

  * What dominates your thinking about human motivation? Is there a particular psychological theory that you tend to gravitate to? For instance, are all things biological? Cognitive? Do you feel a need to simplify?

  * Remember earlier in the quarter when I had you watch the systems within psychology video. This video was a brief introduction to the fact that human motivation is layered. Certainly there are biological reasons for why we do what we do, but there's also learning histories, cognitive processes, personality variables, but also social influences. All of these things are happening all of the time. So somebody says that they're depressed, do you have a tendency to say oh there's something biological wrong? Socially wrong?

  * Keep in mind: how do we measure abnormal behavior?
  * Who has the power to say one thing is normal versus another? Does that power come from cultural norms? Somewhere else? Do we give up this power?  Are we aware we have some power?

  * When a diagnostician gives a diagnosis, who do they serve?

## Do some stuff

* Respond to anything above.  Write maybe 2 or 3 paragraphs.  Yes, this is light.

* Share your writing here in this discussion

* Comment on 2 or 3 of your classmates work inside their google doc.

`r if (knitr:::is_html_output()) '
# References {-}
'`



