---
title: "Week 2"
author: "Brian Holt"
date: "`r Sys.Date()`"
output: 
 html_document:
  toc: true
  toc_float: true
  toc_depth: 4
---

# Orienting comment

If you're relatively new to taking college classes, you might find it disconcerting that we don't simply have you remember a list of vocabulary words. Sometimes that's appropriate. In psychology, as an example coming the term "negative reinforcement" is often confused with a form of punishment.

But this is relatively a shallow level of knowledge. Check out this simple hierarchy pertaining to thinking: [Bloom's taxonomy ](https://uwaterloo.ca/centre-for-teaching-excellence/teaching-resources/teaching-tips/planning-courses-and-assignments/course-design/blooms-taxonomy)

Vocabulary is a very low level type oejof knowledge. And so what are the reasons that human beings create schools and classes such as this is to understand things in a deeper way or in a more complicated Way.

So you may be interested to know in Psychology, what causes attention deficit hyperactivity disorder. You might wonder what causes bipolar disorder or why is it that you  enjoy one type of activity but somebody else does not. Or perhaps how it is that certain romantic partners get along while others do not. These are all interesting questions and Curiosities.

The moment you start getting into those questions, it would be nice if there were short answers but those short answers are usually simplistic and shallow.

So we have to practice, and it is a practice – you don't just get an education and stop learning--you have to keep practicing what you know and how you know it.  And it turns out that is a philosophical question.

So, week 2 is going to be a lot to do with philosophy. It overlaps a little bit with the materials you watched during week one. But the idea is that you're going to have to reflect a little bit about this epistemological question: how do you know what you know


## Read Some stuff


## Do Some stuff

